
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  feature_path: artifacts/data_ingestion/features
  data_URL: "https://drive.google.com/file/d/1ECfl3dtYyfivY8kYPq7RHUBTjC-2vf61/view?usp=share_link"
  data_path: artifacts/data_ingestion/data.zip


data_validation:
  # root_dir: artifacts/data_validation
  # status: artifacts/data_validation/status.txt
  data_yaml: artifacts/data_ingestion/features/data.yaml
  train_path: artifacts/data_ingestion/features/train/images
  valid_path: artifacts/data_ingestion/features/valid/images
  

model_training:
  root_dir: artifacts/model_training
  yolov5_root: yolov5
  yolov5_models: yolov5/models
  custom_yolov5: yolov5/models/custom_yolov5s.yaml
  train_path: yolov5/train.py
  yolov5_runs: artifacts/model_training/yolov5/runs
  history: artifacts/model_training/history
  git_URL: 'https://github.com/ultralytics/yolov5.git'
  

